xlf:
  debug: true
  #host: 0.0.0.0
  port: 2233
database:
  host: localhost
  port: 5432
  user: xlf_sso
  pass: xlf_sso
  name: xlf_sso
  prefix: xlf_
nosql:
  host: localhost
  port: 6379
  database: 0
  password: ''
  prefix: sso